name: Build Wii Core (Dolphin)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build cmake python3

      - name: Install EMSDK
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest
          echo "source $GITHUB_WORKSPACE/emsdk/emsdk_env.sh" >> $GITHUB_ENV

      - name: Load EMSDK
        run: source $GITHUB_WORKSPACE/emsdk/emsdk_env.sh

      - name: Clone Dolphin
        run: |
          git clone https://github.com/dolphin-emu/dolphin.git dolphin-src

      - name: Configure CMake for Wii Core
        run: |
          source $GITHUB_WORKSPACE/emsdk/emsdk_env.sh
          mkdir -p build-wii
          cd build-wii
          emcmake cmake ../dolphin-src \
            -DCMAKE_BUILD_TYPE=Release \
            -DENABLE_GENERIC=ON \
            -DENABLE_QT=OFF \
            -DENABLE_SDL=OFF \
            -DENABLE_X11=OFF \
            -DENABLE_VULKAN=OFF \
            -DENABLE_HEADLESS=ON \
            -DWII_CORE_ONLY=ON \
            -G Ninja \
            -DCMAKE_TOOLCHAIN_FILE=$GITHUB_WORKSPACE/emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake \
            -DCMAKE_CROSSCOMPILING_EMULATOR=$GITHUB_WORKSPACE/emsdk/node/22.16.0_64bit/bin/node

      - name: Build Wii Core with Retry
        run: |
          cd build-wii
          set +e
          ninja -k 1 || true
          echo "Retrying failed files..."
          ninja || true
          set -e

      - name: Link Partial Output to WASM
        run: |
          cd build-wii
          if ls Source/Core/*/*.o > /dev/null 2>&1; then
            emcc Source/Core/*/*.o -o dolphin_wii_core.js -s WASM=1 -s MODULARIZE=1 -s EXPORT_ES6=1 \
              -s 'EXPORTED_RUNTIME_METHODS=["cwrap","ccall"]' || echo "Partial WASM build."
          else
            echo "No .o files found. Build likely failed."
          fi

      - name: Upload Wii Core Build
        uses: actions/upload-artifact@v4
        with:
          name: dolphin-wii-core
          path: build-wii/dolphin_wii_core.*
